#define F_REG_READ      0x03 ///< Read data bytes (as many bytes as needed)
#define F_REG_FAST_READ 0x0b ///< A faster type of read which I don't fully understand
#define F_REG_DREAD     0x3b ///< Uses both MISO and MOSI to read out the data
#define F_REG_PP        0x02 ///< Page Program, for simplicity, leave LSB address byte all 0, write full 256bytes and no more (disregards if otherwise)
#define F_REG_SE        0x20 ///< Sector erase 4k, provide any address in a 4k sector to completely erase it
#define F_REG_BE_32K    0x52 ///< Block erase 32k, provide any address in a 32k block to completely erase it
#define F_REG_BE        0xD8 ///< Block erase 64k, provide any address in a 64k block to completely erase it
#define F_REG_CE        0x60 ///< Chip erase, erases the whole chip (all bits in status must be allowing it)
#define F_REG_RDSFDP    0x5A ///< Read Serial Flash Discoverable Parameter (an ID for the interface structure)
#define F_REG_WREN      0x06 ///< Sets the Write Enable Latch bit (WEL)
#define F_REG_WRDI      0x04 ///< Clears the Write Enable Latch bit (WEL)
#define F_REG_DP        0xb9 ///< Go into Deep Powerdown
#define F_REG_FMEN      0x41 ///< Using factory mode can speed up erase and program speeds, requires controlled temperature and VCC above 3V
#define F_REG_RSTEN     0x66 ///< Software Reset Enable
#define F_REG_RST       0x99 ///< Trigger Software Reset
#define F_REG_RDID      0x9f ///< Read manufacturer ID and device ID
#define F_REG_RES       0xab ///< Read electronic signature
#define F_REG_RDP       0xab ///< Release from Deep Powerdown
#define F_REG_REMS      0x90 ///< Read electronic Manufacturer ID and device ID
#define F_REG_RDSR      0x05 ///< Read status register
#define F_REG_WRSR      0x01 ///< Write status register

/*
 * NOTES:
 *  Status register:
 *      7: status write protect
 *    5-2: level of block protect
 *      1: Write Enable Latch
 *      0: Write In Progress
 *  All writing and erasing needs WEL to be set (with WREN)
 */

// ChatGPT converted diagrams from datasheet to comments: (this is generated by AI (ChatGPT))
/*
 * Figure 11. Program/Erase flow with read array data
 *
 *                     Start
 *                      |
 *                      V
 *               WREN command
 *                      |
 *                      V
 *              RDSR command* 
 *                      |
 *           [Check WEL=1?] -- No --> (Loop back to RDSR command*)
 *                      |
 *                     Yes
 *                      |
 *                      V
 *            Program/erase command
 *                      |
 *                      V
 *   Write program data/address (Write erase address)
 *                      |
 *                      V
 *              RDSR command
 *                      |
 *           [Check WIP=0?] -- No --> (Loop back to RDSR command)
 *                      |
 *                     Yes
 *                      |
 *                      V
 *              RDSR command
 *                      |
 *                      V
 *   Read WEL=0, BP[3:0], QE, and SRWD data
 *                      |
 *                      V
 *   Read array data (same address of PGM/ERS)
 *                      |
 *                      V
 *           [Verify OK?] -- No --> Program/erase fail
 *                      |
 *                     Yes
 *                      |
 *                      V
 *         Program/erase successfully
 *                      |
 *                      V
 *   [Program/erase another block?] -- Yes --> (Loop back to WREN command)
 *                      |
 *                     No
 *                      |
 *                      V
 *         Program/erase completed
 *
 * * Issue RDSR to check BP[3:0].
 */

/*
 * Figure 13. WRSR flow
 *
 *                     Start
 *                      |
 *                      V
 *               WREN command
 *                      |
 *                      V
 *              RDSR command
 *                      |
 *           [Check WEL=1?] -- No --> (Loop back to RDSR command)
 *                      |
 *                     Yes
 *                      |
 *                      V
 *              WRSR command
 *                      |
 *                      V
 *       Write status register data
 *                      |
 *                      V
 *              RDSR command
 *                      |
 *           [Check WIP=0?] -- No --> (Loop back to RDSR command)
 *                      |
 *                     Yes
 *                      |
 *                      V
 *              RDSR command
 *                      |
 *                      V
 *   Read WEL=0, BP[3:0], QE, and SRWD data
 *                      |
 *                      V
 *           [Verify OK?] -- No --> WRSR fail
 *                      |
 *                     Yes
 *                      |
 *                      V
 *            WRSR successfully
 */

/*
 * Figure 32. Factory Mode Chip Erase Flow
 *
 *                     Start
 *                      |
 *                      V
 *               WREN Command
 *                      |
 *                      V
 *              RDSR Command
 *                      |
 *           [Check WEL=1?] -- No --> (Loop back to RDSR Command)
 *                      |
 *                     Yes
 *                      |
 *                      V
 *              FMEN Command
 *                      |
 *                      V
 *         Chip Erase Command*
 *                      |
 *                      V
 *     Factory Mode CE Completed
 *
 * Note: * Please reference Program/Erase flow chart in datasheet.
 */


